#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if [ -f .env ]; then
	export $(echo $(cat .env | sed 's/#.*//g' | xargs) | envsubst)
fi

if [ $DISABLE_HUSKY == 1 ] || [ $DISABLE_HUSKY == true ]; then
	echo -e "\nHusky is disabled!\n"
else
	pnpm lint
fi
